add deploy doc

diff --git a/.github/workflows/deploy_doc.yml b/.github/workflows/deploy_doc.yml
--- a/.github/workflows/deploy_doc.yml
+++ b/.github/workflows/deploy_doc.yml
@@ -36,11 +36,15 @@ jobs:
       - name: Start MkDocs server
         id: start_server
         run: |
-          mkdocs serve -a localhost:1369 &
+          mkdocs serve -a localhost:1369 > mkdocs.log 2>&1 &
 
       - name: Wait for server to start
-        run: sleep 100
+        run: sleep 10
 
       - name: Check if MkDocs server is running
         run: |
-          curl --silent --fail http://localhost:1369 || (echo "MkDocs server failed to start" && exit 1)
+          if ! curl --silent --fail http://localhost:1369; then
+            echo "MkDocs server failed to start. Here's the log:"
+            cat mkdocs.log
+            exit 1
+          fi
