Check for required label

diff --git a/.github/workflows/macOS_test.yml b/.github/workflows/macOS_test.yml
--- a/.github/workflows/macOS_test.yml
+++ b/.github/workflows/macOS_test.yml
@@ -24,11 +24,17 @@ jobs:
     if: |
       !contains(github.event.head_commit.message, '[skip ci]')
       && !contains(github.event.pull_request.title, '[skip ci]')
-      && contains(github.event.pull_request.labels.*.name, 'can_run_test')
     runs-on: macos-13
 
     steps:
-      - uses: actions/checkout@v4
+      - name: Check for required label
+        if: github.event_name == 'pull_request_target' && !contains(github.event.pull_request.labels.*.name, 'lint_pass')
+        run: |
+          echo "The 'lint_pass' label is missing. Skipping CI/CD process."
+          exit 1
+          
+      - name: Checkout code
+        uses: actions/checkout@v4
         with:
           submodules: true
           fetch-depth: 0
@@ -110,7 +116,14 @@ jobs:
     runs-on: macos-13
 
     steps:
-      - uses: actions/checkout@v4
+      - name: Check for required label
+        if: github.event_name == 'pull_request_target' && !contains(github.event.pull_request.labels.*.name, 'lint_pass')
+        run: |
+          echo "The 'lint_pass' label is missing. Skipping CI/CD process."
+          exit 1
+          
+      - name: Checkout code
+        uses: actions/checkout@v4
         with:
           submodules: true
           fetch-depth: 0
diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,6 +25,16 @@ jobs:
       && !contains(github.event.pull_request.title, '[skip ci]')
     runs-on: tps_sco_nv
     steps:
+      - name: Wait for lint label
+        run: |
+          sleep 300
+
+      - name: Check for required label
+        if: github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'lint_pass')
+        run: |
+          echo "The 'lint_pass' label is missing. Skipping CI/CD process."
+          exit 1
+          
       - name: Checkout code
         uses: actions/checkout@v4
 
diff --git a/.github/workflows/win_test.yml b/.github/workflows/win_test.yml
--- a/.github/workflows/win_test.yml
+++ b/.github/workflows/win_test.yml
@@ -5,7 +5,7 @@ on:
     branches:
       - main
   pull_request_target:
-    types: [opened, synchronize, labeled, unlabeled, reopened]
+    types: [opened, synchronize, labeled, reopened]
     branches:
       - main
   workflow_dispatch:
@@ -20,6 +20,9 @@ env:
 
 jobs:
   win-basic_tests:
+    if: |
+      !contains(github.event.head_commit.message, '[skip ci]')
+      && !contains(github.event.pull_request.title, '[skip ci]')
     runs-on: windows-latest
 
     steps:
@@ -122,7 +125,14 @@ jobs:
     runs-on: windows-latest
 
     steps:
-      - uses: actions/checkout@v4
+      - name: Check for required label
+        if: github.event_name == 'pull_request_target' && !contains(github.event.pull_request.labels.*.name, 'lint_pass')
+        run: |
+          echo "The 'lint_pass' label is missing. Skipping CI/CD process."
+          exit 1
+
+      - name: Checkout code
+        uses: actions/checkout@v4
         with:
           submodules: true
           fetch-depth: 0
